export const SliderData = [
    {
      image:
       'https://i.imgur.com/HoORf5F.jpg', 
    }, 
    {
      image:
       'https://i.imgur.com/Ax8CSW5.jpg', 
    }, 
    {
      image:
      'https://i.imgur.com/2344B5A.jpg',
    },
    {
      image:
      'https://i.imgur.com/1IHb9bu.jpg',
    },
    {
      image:
      'https://i.imgur.com/jR1yfJV.jpg',
    },
    {
      image:
      'https://i.imgur.com/md0utu3.jpg',
    },
    {
      image:
      'https://i.imgur.com/reiLLOu.jpg',
    },
    {
      image:
      'https://i.imgur.com/gLhMVgU.jpg',
    }
  ];
