import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'
// import Slider from '../components/Slider';
// import { SliderData } from '../components/SliderData';
import About from '../components/About'
import Solution from '../components/Solution'
// import Footer from '../components/Footer'
import ContactUs from '../components/ContactUs.tsx'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Give Water Give Life</title>
        <meta
          name="Saving a Life with One Cup at a Time"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero
        heading="Give Water Give Life"
        message="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  "
      />
      <About />
      <ContactUs />
    </div>
  )
}
