import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Give Water Give Life</title>
        <meta name="Saving a Life with One Cup at a Time" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero heading='Give Water Give Life' message="One Survivor's Story"/>
    </div>
  );
}
