import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar.tsx'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Give Water Give Life</title>
        <meta name="Saving a Life with One Cup at a Time" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </div>
  )
}
